# Generated by Django 5.2.4 on 2025-07-28 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0004_course_academic_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='academic_year',
        ),
    ]
