# Generated by Django 5.2.4 on 2025-08-11 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0005_remove_course_academic_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrolment',
            unique_together={('student', 'course')},
        ),
    ]
