# Generated by Django 5.2.4 on 2025-08-12 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0006_alter_enrolment_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklyschedule',
            old_name='weekday',
            new_name='iso_weekday',
        ),
    ]
