# Generated by Django 5.2.4 on 2025-08-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0007_rename_weekday_weeklyschedule_iso_weekday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('unregistered', 'Unregistered'), ('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], max_length=20),
        ),
    ]
