# Generated by Django 5.2.4 on 2025-08-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0008_alter_attendancerecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
