# Generated by Django 5.2.4 on 2025-10-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0009_lesson_start_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='landing_url',
            field=models.CharField(db_default='lessons-today', max_length=100),
        ),
    ]
